coverage:
  status:
    project:
      default:
        enabled: yes
        target: 50
        threshold: "100%"
        informational: true
    patch:
      enabled: yes
      target: 50
      threshold: "100%"
      informational: true

comment:
  require_changes: true

ignore:
  - "**/ent"
  - "**/mocks"
  - "**/stubs"