coverage:
  status:
    project:
      default:
        enabled: yes
        target: 50
        threshold: 50%
        informational: true
        if_ci_failed: success
    patch: false

comment:
  require_changes: true

ignore:
  - "**/ent"
  - "**/mocks"
  - "**/stubs"