run:
  issues-exit-code: 0

issues:
  new: true

output:
  sort-results: true
  sort-order:
    - severity
    - file
    - linter

  show-stats: true

linters:
  enable-all: true

  disable:
    - execinquery
    - gomnd
    - depguard